# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# github action to deploy event eagle api to azure


name: Deploy Event Eagle API

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: dotnet restore ./backend/backend.csproj

      - name: Build
        run: dotnet build ./backend/backend.csproj --configuration Release --no-restore

      



